version: 2
jobs:
  unit-test-job:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install yarn
          command: yarn

      - run:
          name: Run frontend unit tests
          command: |
            yarn test
  lint-job:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install yarn
          command: yarn

      - run: yarn lint

  deploy-job:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to github pages
          command: yarn deploy
      - run:
        command: |
          ngh --token $TOKEN
workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test-job
      - lint-job
      - deploy-job:
          requires:
            - unit-test-job
          filters:
            branches:
              only: master